### PR TITLE
Adds NestJS v7 to peer dependencies

### PR DESCRIPTION
**Pull request by iamjoeker**
### All Submissions:

- [x] Have you followed the guidelines in our Contributing section?
- [x] Have you checked to ensure there aren't other open
      [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you linted your code locally prior to submission?

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like
      us to include them?
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

---

Include NestJS v7 in the peer dependencies.

### CODE REVIEW

**Comment by 0xb4lamx** [comment]
up

**Comment by iamjoeker** [comment]
@dhaspden Any chance of merging this? v7 is already listed as dev dependencies of the project and this would eliminate install warnings for those using v7

**Comment by fjcero** [comment]
What else is needed to upgrade dependencies? Version bump?

**Review by dhaspden — APPROVED** [review]

**Comment by dhaspden** [comment]
Sorry for the delay, thanks for the contribution @iamjoeker!

**Comment by fjcero** [comment]
Thanks @dhaspden !!

**Pull request merged**
